### ISSUE TITLE
客户端测试次数调大后，服务器与注册中心的连接超时

### ISSUE THREAD

**Issue by AnliClark** [AnliClark/A-Simple-RPC#1]
当我试图增大客户端应用上的测试次数时，我发现docker上的日志显示客户端无法找到服务：
![image](https://github.com/user-attachments/assets/4ff77016-587a-4efe-a7ab-005b8342fe13)
服务端的日志如下：
![image](https://github.com/user-attachments/assets/128e3041-ee9a-498c-a69f-187075527d31)
注册中心的日志如下：
![image](https://github.com/user-attachments/assets/0e0d8f05-f79d-4de7-a268-4cd456a69ce1)
我注意到您的代码似乎是有一次超时以后重新建立连接的机会的，但是它似乎没有起效。
在之后的观察中，服务端与注册中心的日志一直没有变化，这个bug似乎导致了服务端与注册中心的崩溃。

**Comment by pathwoven** [comment]
感谢你的反馈，我已经将它加入到了我的待办事项中

**Comment by pathwoven** [comment]
已解决
